management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    tags:
      application: my-project

server:
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  task:
    execution:
      pool:
        core-size: 500
        max-size: 500
        queue-capacity: 200
        keep-alive: 30s