env:
  S3_BUCKET_NAME: clothstar-bucket
  CODE_DEPLOY_APP_NAME: clothstar-deploy-v2
  DEPLOYMENT_GROUP_NAME: clothstar_deploy
  ZIP_FILE_NAME: clothstar-deploy.zip

name: aws-deploy
on:
  push:
    branches: develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      - name: Build with Gradle
        run: ./gradlew build
      - name: Make zip file
        run: zip -r ./$ZIP_FILE_NAME .
        shell: bash
